spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor?createDatabaseIfNotExist=true
    username: root
  application:
    name: 'fornecedor'

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


